steps:
  - id: terraform-init
    name: hashicorp/terraform:1.3.5
    args: ["init", "-backend-config=bucket=prd-mufg-scrape-tfstate"]
    dir: "terraform"
    env:
      - "TF_VAR_gcp_project=$PROJECT_ID"

  - id: terraform-apply
    name: hashicorp/terraform:1.3.5
    args: ["apply", "-var-file=prd.tfvars", "-auto-approve"]
    dir: "terraform"
    env:
      - "TF_VAR_gcp_project=$PROJECT_ID"
